#!/usr/bin/env python3
"""
Generates one JSON Schema per artifact type from `artifact-types.yaml`.

    python generate.py            regenerate schemas/framework/<type>/v1.json
    python generate.py --check    exit non-zero if what is on disk diverges

WHY GENERATED AND NOT HAND WRITTEN. Twenty-eight schemas sharing nine tenths of their
structure, maintained by hand, diverge. The registry is the source; these files are its
projection. Duplication inside generated output is not the duplication the framework
forbids, because there is still one place to change.

WHY `--check` EXISTS. A generated file that nobody regenerates is worse than a hand
written one, because everyone assumes something keeps it true. In CI this is what notices
that a schema was edited by hand, or that the registry moved and the schemas did not.

WHY THE SCHEMAS ARE SELF CONTAINED. No `$ref` between files. A consumer that wants to
check one artifact needs one file and no resolver, which is the difference between
"an agent can verify itself" and "an agent needs a schema store first".

WHAT THESE SCHEMAS CHECK: the front matter. Presence of the required fields, the legal
values of `lifecycle`, `status` and `scope`, the fields that become required once a
document declares itself `active`, the `generated_by` that stands in for `owners` on the
types no person writes, and the cardinality of `products` where it is exactly one.

WHAT THEY DO NOT CHECK, and what a validator still has to: the mandatory sections, which
live in the markdown body and are not expressible here; staleness of the living
documents; unique ids; dangling references; cycles in the supersedence chain; anything
cross-artifact. Passing the schema is not passing the gate, and the two must not get
confused: the section list stays in the registry for exactly this reason.

ONE NOTE FOR WHOEVER WIRES THIS INTO A VALIDATOR. JSON Schema validates JSON, and YAML
front matter does not parse to JSON: `created: 2026-07-27` becomes a `date` object, not a
string. Serialize dates before validating, or every artifact fails on a field that is
correct. That is also why no format or pattern is imposed on `created` and `last_review`
here: choosing one means choosing the serialization first, and the registry does not say.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("Needs pyyaml:  pip install pyyaml")


HERE = Path(__file__).resolve().parent
REGISTRY = HERE / "artifact-types.yaml"
OUT_ROOT = HERE / "framework"

BANNER = ("Generated by schemas/generate.py from schemas/artifact-types.yaml. "
          "Do not edit by hand: run the generator.")


def non_placeholder(placeholders: list[str]) -> dict:
    """A field that is present but still carries its template placeholder is missing.

    A placeholder that reaches a real repository reads as a real value to anything that
    does not know the template, and `verified_against: COMMIT_HASH` is the worst case of
    it: a document that claims to have been checked against a commit.
    """
    return {"type": "string", "minLength": 1, "not": {"enum": list(placeholders)}}


def build(name: str, spec: dict, registry: dict) -> dict:
    schema_id = f"framework/{name}/v1"
    base_required = list(registry["base_required"])
    placeholders = list(registry["placeholders"]["enforced"])

    properties: dict = {
        "schema": {"const": schema_id},
        "artifact_type": {"const": name},
        "lifecycle": {"const": spec["lifecycle"]},
        "status": {"enum": list(spec["status"])},
    }
    required = list(base_required)

    # A generated type has no owner, it has a generator. The slot is the same one, so
    # `base_required` stays a flat rule with no exception to remember.
    if spec.get("generated"):
        required[required.index("owners")] = "generated_by"
        properties["generated_by"] = non_placeholder(placeholders)
    else:
        properties["owners"] = {"type": "array", "minItems": 1}

    properties["created"] = {}

    # Cardinality on `products`, where the template used to say it with a singular field
    # name. An unrecognised value stops the generator rather than being skipped: a
    # constraint quietly ignored is the one failure this whole file exists to avoid.
    cardinality = spec.get("products")
    if cardinality == "exactly-one":
        properties["products"] = {"type": "array", "minItems": 1, "maxItems": 1}
        required.append("products")
    elif cardinality is not None:
        raise SystemExit(f"{name}: unknown value for `products`: {cardinality!r}")

    # Type specific enums. `scope` on a decision record is not optional: it is what says
    # whether the decision is about the product, the architecture or the platform, and a
    # decision record without it is unfiled.
    for field, values in (spec.get("enums") or {}).items():
        properties[field] = {"enum": list(values)}
        if field not in required:
            required.append(field)

    # A field that maps one identifier to a verdict about it. The `ICG` needs this and
    # nothing else did: a triage classifies many candidates in one document, so the thing
    # to pin is not a single value but a value per candidate. Written as front matter
    # rather than as a table in the body because that is the whole reason the gate is
    # getting an artifact: `CHG001` and `CHG002` are switched off precisely because the
    # routing was prose, and a check reading prose is the failure they were disabled over.
    for field, rule in (spec.get("maps") or {}).items():
        if "one_of" in rule:
            value: dict = {"enum": list(rule["one_of"])}
        elif "any_of" in rule:
            value = {"type": "array", "items": {"enum": list(rule["any_of"])},
                     "minItems": 1, "uniqueItems": True}
        elif "fields" in rule:
            # A record per key rather than a verdict per key. The code map needs this:
            # a repository is not one value, it is a URL and a sentence saying what is in
            # it, and an agent told only a name still cannot go and read anything.
            f = rule["fields"]
            props = {k: {"type": "string", "minLength": 1}
                     for k in list(f.get("required", [])) + list(f.get("optional", []))}
            # A field of the record can carry a closed vocabulary. Without this a typo in a
            # status is a string like any other, and the map that was supposed to be the
            # checkable half of the document goes back to being prose with colons in it.
            for k, values in (f.get("enums") or {}).items():
                if k not in props:
                    raise SystemExit(f"{name}.maps.{field}.enums: {k!r} is not a field")
                props[k] = {"enum": list(values)}
            value = {"type": "object", "properties": props,
                     "required": list(f.get("required", [])),
                     "additionalProperties": False}
        else:
            raise SystemExit(f"{name}.maps.{field}: needs `one_of`, `any_of` or `fields`")
        # The keys are constrained as well as the values, and the keys are the part that
        # matters more: they are the identifiers the rest of the framework joins on. With
        # them open, `routing: {banana: none}` validated, and a mistyped candidate then
        # stayed reported as never triaged with nothing anywhere saying why.
        # `NNN` is allowed beside a real number because the templates have to validate
        # against their own schemas, and a template cannot carry a real identifier. That
        # rule is worth more than closing this hole: the template is the thing people copy,
        # and one that fails the check it teaches is worse than a permissive pattern. `NNN`
        # is in the registry's placeholder list and not in the enforced one, so the
        # framework already decided it reaching a repository is not a blocking error.
        #
        # `keys` overrides the pattern for a map whose keys are not framework identifiers.
        # Repository names are the case: they are somebody's slugs, not `SIG-001`, and
        # forcing them into the identifier shape would make the field unusable rather than
        # safe.
        ids = "|".join(registry["id_prefixes"])
        key_pattern = rule.get("keys") or rf"^({ids})-(\d{{3,}}|NNN)$"
        properties[field] = {"type": "object", "minProperties": 1,
                             "propertyNames": {"pattern": key_pattern},
                             "additionalProperties": value}
        if rule.get("required") and field not in required:
            required.append(field)

    for field in spec.get("required", []):
        properties[field] = non_placeholder(placeholders)
        if field not in required:
            required.append(field)

    out: dict = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": schema_id,
        "title": name,
        "description": BANNER,
        "type": "object",
        "properties": properties,
        "required": required,
    }

    # Fields required only from `active`. They attest a fact about the world, and in
    # draft that fact does not exist yet: demanding them earlier would forbid designing
    # before implementing, which is the order the framework prescribes.
    conditional = spec.get("required_if_active", [])
    if conditional:
        out["allOf"] = [{
            "if": {"properties": {"status": {"const": "active"}}, "required": ["status"]},
            "then": {
                "required": list(conditional),
                "properties": {f: non_placeholder(placeholders) for f in conditional},
            },
        }]

    return out


def render(schema: dict) -> str:
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


# ─────────────────────────────────────────────────────────────────────────────
# The catalog tables
#
# The same twenty eight artifacts were listed by hand in two documents, and the two had
# already drifted: `DC` was "living, versioned" in one and "living" in the other, and the
# same for `EVP` and `IMP`. That is the framework breaking its own single rule inside its
# own reference document, five commits after it was written. Now both are projections of
# the registry, and the drift is not something to be careful about, it is impossible.

REGION = re.compile(r"(?P<open><!-- generated: (?P<name>[a-z-]+) -->\n)"
                    r".*?"
                    r"(?P<close>\n<!-- /generated -->)", re.S)


def artifact_class(spec: dict) -> str:
    note = spec.get("class_note")
    return f"{spec['lifecycle']}, {note}" if note else spec["lifecycle"]


def catalog_table(registry: dict, header: list[str], row) -> str:
    # The line above the table is not decoration. The `<!-- generated -->` marker is
    # invisible once the markdown is rendered, so somebody reading this on the web sees an
    # ordinary table and edits it, and the edit is gone at the next run without anybody
    # being told. The warning has to be visible to the person holding the cursor.
    lines = ["*Generated from `schemas/artifact-types.yaml`. Edit that file, not this "
             "table.*", "",
             "| " + " | ".join(header) + " |",
             "|" + "|".join("---" for _ in header) + "|"]
    lines += [row(spec) for spec in registry["types"].values()]
    return "\n".join(lines)


def catalogs(registry: dict) -> dict[str, str]:
    return {
        "catalog": catalog_table(
            registry, ["ID", "Name", "Class", "Axis", "Born in"],
            lambda s: f"| `{s['id']}` | {s['name']} | {artifact_class(s)} "
                      f"| {s['axis']} | {s['born_in']} |"),
        "catalog-templates": catalog_table(
            registry, ["File", "Artifact", "Class", "Naming"],
            lambda s: f"| `{Path(s['template']).name}` | {s['name']} "
                      f"| {artifact_class(s)} | `{s['path']}` |"),
    }


def rewrite_regions(text: str, tables: dict[str, str], path: Path) -> str:
    def sub(m):
        name = m.group("name")
        if name not in tables:
            sys.exit(f"{path}: unknown generated region {name!r}")
        return m.group("open") + tables[name] + m.group("close")
    return REGION.sub(sub, text)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("--check", action="store_true",
                    help="do not write: exit non-zero if disk diverges from the registry")
    args = ap.parse_args()

    registry = yaml.safe_load(REGISTRY.read_text(encoding="utf-8"))
    types = registry["types"]

    wanted = {OUT_ROOT / name / "v1.json": render(build(name, spec, registry))
              for name, spec in types.items()}

    tables = catalogs(registry)
    for doc in (HERE.parent / "FRAMEWORK.md", HERE.parent / "templates" / "README.md"):
        current = doc.read_text(encoding="utf-8")
        rewritten = rewrite_regions(current, tables, doc)
        if REGION.search(current) is None:
            sys.exit(f"{doc}: no generated region found. The catalog has nowhere to go.")
        wanted[doc] = rewritten

    # A type removed from the registry leaves its schema behind, and a stale schema is
    # indistinguishable from a current one to whoever finds it.
    existing = set(OUT_ROOT.rglob("v1.json")) if OUT_ROOT.exists() else set()
    orphans = sorted(existing - set(wanted))

    if args.check:
        diverging = sorted(
            p for p, text in wanted.items()
            if not p.exists() or p.read_text(encoding="utf-8") != text
        )
        for p in diverging:
            state = "missing" if not p.exists() else "differs from the registry"
            print(f"x {p.relative_to(HERE.parent)}: {state}")
        for p in orphans:
            print(f"x {p.relative_to(HERE.parent)}: no such type in the registry")
        if diverging or orphans:
            print(f"\n{len(diverging) + len(orphans)} file(s) out of date. "
                  f"Run: python {Path(__file__).name}")
            return 1
        docs = [p for p in wanted if p.suffix == ".md"]
        print(f"{len(wanted) - len(docs)} schemas and {len(docs)} catalog tables "
              "up to date with the registry.")
        return 0

    for p, text in wanted.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
    for p in orphans:
        p.unlink()
        try:
            p.parent.rmdir()
        except OSError:
            pass

    docs = [p for p in wanted if p.suffix == ".md"]
    print(f"{len(wanted) - len(docs)} schemas written to {OUT_ROOT.relative_to(HERE.parent)}/")
    print(f"{len(docs)} catalog table(s) rewritten in: "
          + ", ".join(sorted(str(p.relative_to(HERE.parent)) for p in docs)))
    if orphans:
        print(f"{len(orphans)} orphan schema(s) removed: "
              + ", ".join(str(p.relative_to(HERE.parent)) for p in orphans))
    return 0


if __name__ == "__main__":
    sys.exit(main())
